-- 코드를 입력하세요
SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B 
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID 
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
