-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE AS ONLINE 
WHERE YEAR(ONLINE.SALES_DATE) = 2022 AND MONTH(ONLINE.SALES_DATE) = 03
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID , SALES_AMOUNT
FROM OFFLINE_SALE AS OFFLINE 
WHERE YEAR(OFFLINE.SALES_DATE) = 2022 AND MONTH(OFFLINE.SALES_DATE) = 03
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;