-- 코드를 입력하세요
SELECT C.CAR_ID,C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE

WHERE C.CAR_TYPE IN ('세단','SUV') 
AND C.CAR_ID NOT IN (SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE START_DATE <= '2022-11-30'
AND
END_DATE >= '2022-11-01')
AND D.DURATION_TYPE = '30일 이상'

HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC


