-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR,MONTH(O.SALES_DATE) AS MONTH,COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
 ROUND(COUNT(DISTINCT U.USER_ID) / 
      (SELECT COUNT(*)
       FROM USER_INFO
       WHERE YEAR(JOINED) = 2021
),1) AS PURCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE)