-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT)  AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY O.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC