-- 코드를 입력하세요
SELECT A.APNT_NO,P.PT_NAME,P.PT_NO,A.MCDP_CD,D.DR_NAME,A.APNT_YMD
FROM APPOINTMENT A JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON  A.MDDR_ID = D.DR_ID
WHERE (YEAR(A.APNT_YMD) = '2022' AND MONTH(A.APNT_YMD) = '04' AND DAY(A.APNT_YMD) = '13') AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC