-- 코드를 작성해주세요
SELECT YEAR,M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E
JOIN(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR 
ORDER BY M.YEAR ASC,YEAR_DEV ASC;