-- 코드를 작성해주세요

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FIN ON FI.FISH_TYPE = FIN.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN(
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE 
)